### ISSUE TITLE
Error I got while trying to make a captioned gif

### ISSUE THREAD

**Issue by Koolfudsim** [esmBot/esmBot#105]
Message: Error: 500 Internal Server Error on POST /api/v7/channels/703663532918702160/messages

Stack Trace: DiscordHTTPError: 500 Internal Server Error on POST /api/v7/channels/703663532918702160/messages
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/eris-sharder/node_modules/eris/lib/rest/RequestHandler.js:75:15)
    at EventEmitter.<anonymous> (/home/esmBot/esmBot/node_modules/eris-sharder/src/sharding/clustermanager.js:327:71)
    at EventEmitter.emit (node:events:365:28)

**Comment by TheEssem** [comment]
Seems like an issue with either Eris or Discord themselves. I'm not sure if I can fix this on my end.
