### ISSUE TITLE
Bot fails to send help command (appears unrelated to #11)

### ISSUE THREAD

**Issue by TheEgghead27** [esmBot/esmBot#112]
**Command that caused the error**
`help`

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.
N/A

**To Reproduce**
1. Direct Message esmBot asking for the help command.
2. esmBot tries to send the message
3. See error
**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?
No

**Error file**
```
Message: TypeError: message.channel.createMessage is not a function

Stack Trace: TypeError: message.channel.createMessage is not a function
    at module.exports (/home/esmBot/esmBot/utils/pagination/pagination.js:7:43)
    at HelpCommand.run (/home/esmBot/esmBot/commands/general/help.js:91:14)
    at module.exports (/home/esmBot/esmBot/events/messageCreate.js:89:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Additional context**

**Comment by TheEssem** [comment]
This alongside #111 are both fixed with 56113a1. Will be part of the 1.5.2 release.
