### ISSUE TITLE
Loop ended before all servers could be checked

### ISSUE THREAD

**Issue by TypicalJam** [esmBot/esmBot#133]
Message: Error: Loop ended before all servers could be checked

Stack Trace: Error: Loop ended before all servers could be checked
    at getIdeal (/home/esmBot/esmBot/utils/image.js:173:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/home/esmBot/esmBot/utils/image.js:178:25)

**Comment by TheEssem** [comment]
Seems to no longer occur, closing.

**Comment by TheEssem** [comment]
Never mind, I might take a closer look at this now that I know the cause.

**Comment by TheEssem** [comment]
This seems to have long been fixed, closing.
