### ISSUE TITLE
Error while &stats command, On the main bot.

### ISSUE THREAD

**Issue by cybrpop** [esmBot/esmBot#137]
**Command that caused the error**
`&stats`

**To Reproduce**
1. do `&stats`

**Self-hosted instance?**
No.

**Error file**

```
Message: TypeError: Cannot read property 'username' of undefined

Stack Trace: TypeError: Cannot read property 'username' of undefined
    at StatsCommand.run (/home/esmBot/esmBot/commands/general/stats.js:19:63)
    at module.exports (/home/esmBot/esmBot/events/messageCreate.js:90:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Additional context**
I ran the command while the bot was almost processed the image and was bout to post it i think, here's a image,
![image](https://i.imgur.com/JZOZa1Y.png)
(don't mind my nickname)

**Comment by TheEssem** [comment]
Fixed on master with 0af6533
