### ISSUE TITLE
errors with command parser

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#140]
`meme --_`
```
Message: TypeError: args.filter is not a function

Stack Trace: TypeError: args.filter is not a function
    at MemeCommand.params (/home/sam/sources/esmbot/commands/image-editing/meme.js:5:26)
    at MemeCommand.run (/home/sam/sources/esmbot/classes/imageCommand.js:86:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
`meme --_ a`
```
[2021-07-11 15:43:44]: [ERROR] - Cluster 0 | Unhandled Rejection at: Promise {
  <rejected> TypeError: args._.push is not a function
      at module.exports (/home/sam/sources/esmbot/utils/parseCommand.js:46:16)
      at module.exports (/home/sam/sources/esmbot/events/messageCreate.js:56:18)
      at Client.emit (node:events:394:28)
      at Shard.emit (/home/sam/sources/esmbot/node_modules/eris/lib/gateway/Shard.js:240:26)
      at Shard.wsEvent (/home/sam/sources/esmbot/node_modules/eris/lib/gateway/Shard.js:837:26)
      at Shard.onPacket (/home/sam/sources/esmbot/node_modules/eris/lib/gateway/Shard.js:400:26)
      at Shard._onWSMessage (/home/sam/sources/esmbot/node_modules/eris/lib/gateway/Shard.js:2185:29)
      at WebSocket.emit (node:events:394:28)
      at Receiver.receiverOnMessage (/home/sam/sources/esmbot/node_modules/ws/lib/websocket.js:845:20)
      at Receiver.emit (node:events:394:28)
} reason: TypeError: args._.push is not a function
```
`help --_`
```
Message: TypeError: Cannot read property 'toLowerCase' of undefined

Stack Trace: TypeError: Cannot read property 'toLowerCase' of undefined
    at HelpCommand.run (/home/sam/sources/esmbot/commands/general/help.js:14:62)
    at module.exports (/home/sam/sources/esmbot/events/messageCreate.js:92:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TheEssem** [comment]
Fixed by e640cc8
