### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by r0xANDt0l** [esmBot/esmBot#145]
### Command that caused the error

&caption POV: bottas loses his seat

### Image that caused the error

https://imgur.com/a/pj5zqNj

### Steps to reproduce

1. Post imgur link with gif
2. Post &caption command
3. Wait 20 mins +-

### Self-hosted instance?

No

### Error file

```
Message: Error: Job timed out

Stack Trace: Error: Job timed out
    at WebSocket.<anonymous> (/home/esmBot/esmBot/utils/image.js:92:45)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/ws/lib/websocket.js:833:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/ws/lib/receiver.js:502:14)
    at Receiver.getData (/home/esmBot/esmBot/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/esmBot/esmBot/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/esmBot/esmBot/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
```

**Comment by TheEssem** [comment]
Error message fixed with 1.6.0, it should now give a more informative message on timeout
