### ISSUE TITLE
Tags longer than 2000 characters

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#151]
When trying to display a tag longer than 2000 characters, the bot returns an error:
```
Message: DiscordRESTError [50035]: Invalid Form Body
  content: Must be 2000 or fewer in length.
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:75:15)
    at Client.createMessage (/home/esmBot/esmBot/node_modules/eris/lib/Client.js:633:36)
    at module.exports (/home/esmBot/esmBot/events/messageCreate.js:99:20)
    at runMicrotasks (<anonymous>)
```
It would be possible to display these tags inside an embed's description, because the character limit for that is 4096.

**Comment by TheEssem** [comment]
Fixed with #182
