### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Wawa-byte** [esmBot/esmBot#154]
### Command that caused the error

&fakeping

### Steps to reproduce

1. Go to 'Discord channel and run the command &fakeping '
2. See error

### Self-hosted instance?

No

### Error file

```
Message: FetchError: request to http://balls.dm4uz3.pt:2333/loadtracks?identifier=https://raw.githubusercontent.com/esmBot/esmBot/master/assets/audio/ping.ogg failed, reason: connect EHOSTUNREACH 188.37.186.124:2333
    at ClientRequest.<anonymous> (/home/esmBot/esmBot/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}

Stack Trace: FetchError: request to http://balls.dm4uz3.pt:2333/loadtracks?identifier=https://raw.githubusercontent.com/esmBot/esmBot/master/assets/audio/ping.ogg failed, reason: connect EHOSTUNREACH 188.37.186.124:2333
    at ClientRequest.<anonymous> (/home/esmBot/esmBot/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by TheEssem** [comment]
Seems that one of the image servers went down, I've removed it from the list for the time being. Will re-add it once it comes back up.
