### ISSUE TITLE
Bruh Command in thread

### ISSUE THREAD

**Issue by LizAtNymph** [esmBot/esmBot#199]
### Command that caused the error

Bruh

### Steps to reproduce

1. Go to 'a thread'
2. Type 'Bruh'
3. Hit Return

### Self-hosted instance?

No

### Error file

```
Message: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new BruhCommand (file:///home/esmBot/esmBot/commands/soundboard/bruh.js?v=113:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Stack Trace: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new BruhCommand (file:///home/esmBot/esmBot/commands/soundboard/bruh.js?v=113:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional context

User just typed "Bruh", as he always does, and emsBot thought it was a command. This was in a thread in a channel. Typing "Bro" also produced this error.

**Comment by TheEssem** [comment]
Fixed with 5db8873
