### ISSUE TITLE
&speed command "Invalid file object"

### ISSUE THREAD

**Issue by flleeppyy** [esmBot/esmBot#230]
### Command that caused the error

&speed 2

### Image that caused the error

https://cdn.discordapp.com/attachments/825455881796845618/939416814390243329/aa.mp4

### Steps to reproduce

call the command with the attached file (using link doesn't work)

### Self-hosted instance?

No

### Error file

```
Message: {
  message: 'Invalid file object',
  name: 'Error',
  stack: 'Error: Invalid file object\n' +
    '    at actualCall (/home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:139:35)\n' +
    '    at SequentialBucket.check (/home/esmBot/esmBot/node_modules/eris/lib/util/SequentialBucket.js:56:28)\n' +
    '    at SequentialBucket.queue (/home/esmBot/esmBot/node_modules/eris/lib/util/SequentialBucket.js:75:14)\n' +
    '    at /home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:391:40\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at RequestHandler.request (/home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:77:16)\n' +
    '    at Admiral.centralApiRequest (/home/esmBot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:1300:34)\n' +
    '    at EventEmitter.<anonymous> (/home/esmBot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:430:34)\n' +
    '    at EventEmitter.emit (node:events:520:28)\n' +
    '    at Worker.<anonymous> (node:internal/cluster/primary:186:13)'
}

Stack Trace: Error: Invalid file object
    at actualCall (/home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:139:35)
    at SequentialBucket.check (/home/esmBot/esmBot/node_modules/eris/lib/util/SequentialBucket.js:56:28)
    at SequentialBucket.queue (/home/esmBot/esmBot/node_modules/eris/lib/util/SequentialBucket.js:75:14)
    at /home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:391:40
    at new Promise (<anonymous>)
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/eris/lib/rest/RequestHandler.js:77:16)
    at Admiral.centralApiRequest (/home/esmBot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:1300:34)
    at EventEmitter.<anonymous> (/home/esmBot/esmBot/node_modules/eris-fleet/dist/sharding/Admiral.js:430:34)
    at EventEmitter.emit (node:events:520:28)
    at Worker.<anonymous> (node:internal/cluster/primary:186:13)
```

**Comment by TheEssem** [comment]
The bot does not support video files at the moment, so the bot probably used a different image.

What was the last file sent in the channel before the video?

**Comment by TheEssem** [comment]
Closing until OP responds.
