### ISSUE TITLE
Error using soundboard commands in DMs

### ISSUE THREAD

**Issue by General-Mudkip** [esmBot/esmBot#240]
### Command that caused the error

boom

### Image that caused the error

N/A

### Steps to reproduce

1. DM esmBot "boom" or any other soundboard command
2. Should return error message/play sound while in VC
3. Actually returns error txt file

### Self-hosted instance?

No

### Error file

```
Message: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new ExplosionCommand (file:///home/esmBot/esmBot/commands/soundboard/explosion.js?v=121:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Stack Trace: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new ExplosionCommand (file:///home/esmBot/esmBot/commands/soundboard/explosion.js?v=121:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional context

Was trying to see if I could run soundboard commands in a VC by DMing instead of spamming a bot channel.

**Comment by TheEssem** [comment]
Fixed with f0f0bff8f33182c4c53089cf5d8c0b8a1f33cc2b
