### ISSUE TITLE
Saying "Stop" in a thread causes an error

### ISSUE THREAD

**Issue by samast2010** [esmBot/esmBot#261]
### Command that caused the error

No command

### Steps to reproduce

1. Go to any thread in a text channel
2. Say the word "Stop"

### Self-hosted instance?

No

### Error file

```
Message: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new StopCommand (file:///home/esmBot/esmBot/commands/music/stop.js?v=116:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Stack Trace: TypeError: Cannot read properties of undefined (reading 'id')
    at new MusicCommand (file:///home/esmBot/esmBot/classes/musicCommand.js:7:57)
    at new StopCommand (file:///home/esmBot/esmBot/commands/music/stop.js?v=116:4:1)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:104:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TheEssem** [comment]
This is related to a limitation with Eris and how it interacts with the Discord API; at first, it thinks that the thread channel is a DM channel, so the bot falls back to its DM behavior (prefixless commands). Every subsequent message should be ignored by the bot, however, since the channel type is properly cached by the bot and Discord's gateway.

This should (hopefully) be fixed by the move to slash commands.

**Comment by samast2010** [comment]
Ah alright, I see.
