### ISSUE TITLE
Massive Error on Command

### ISSUE THREAD

**Issue by Conquestors** [esmBot/esmBot#285]
### Command that caused the error

stats

### Image that caused the error

https://i.imgur.com/s2375lH.png

### Steps to reproduce

1. Type the prefix along with the command `stats`
2. You will encounter a massive error upon execution.

### Self-hosted instance?

No

### Error file

```
Message: TypeError: Cannot read properties of null (reading 'username')
    at StatsCommand.run (file:///home/esmBot/esmBot/commands/general/stats.js?v=45:22:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///home/esmBot/esmBot/events/messageCreate.js:105:20)

Stack Trace: TypeError: Cannot read properties of null (reading 'username')
    at StatsCommand.run (file:///home/esmBot/esmBot/commands/general/stats.js?v=45:22:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///home/esmBot/esmBot/events/messageCreate.js:105:20)
```

### Additional context

Looks to be that the bot cannot read the user's username, or user object.

**Comment by TheEssem** [comment]
Should be fixed on the main branch with 9ff4126
