### ISSUE TITLE
invalid token error should be friendlier

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#320]
currently trying to run esmbot with an invalid token prints a 100+ line error which should be simplified to a one line "invalid token"
```
[2022-10-30 23:36:03]: [INFO] - Finished loading events. 
/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/Client.js:136
            throw new Error("Failed to get gateway information.", { cause: err });
                  ^

Error: Failed to get gateway information.
    at Client.connect (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/Client.js:136:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: DiscordRESTError: 401: Unauthorized on GET /api/v10/gateway/bot
      at RequestHandler.request (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
      at RequestHandler.authRequest (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
      at RESTManager.authRequest (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
      at RESTManager.getBotGateway (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:53:21)
      at Client.connect (/home/sam/sources/esmbot/node_modules/.pnpm/oceanic.js@1.2.1_bufferutil@4.0.7/node_modules/oceanic.js/dist/lib/Client.js:128:40)
      at init (file:///home/sam/sources/esmbot/app.js:213:10) {
    code: 0,
    method: 'GET',
    resBody: { message: '401: Unauthorized', code: 0 },
    response: Response {
```
followed by 81 lines of response information and then
```
    }
  }
}

Node.js v18.10.0
```

**Comment by TheEssem** [comment]
Done with #456 and 0eabee9aa94d530af6a24fff1f6cfa991ac1f571
