### ISSUE TITLE
it dont work'

### ISSUE THREAD

**Issue by redentgit** [esmBot/esmBot#33]

**Comment by redentgit** [comment]
screen shot thing just dont work

**Comment by redentgit** [comment]
Message: FetchError: request to http://172.17.0.2:9222/json/version failed, reason: connect EHOSTUNREACH 172.17.0.2:9222

Stack Trace: FetchError: request to http://172.17.0.2:9222/json/version failed, reason: connect EHOSTUNREACH 172.17.0.2:9222
    at ClientRequest.<anonymous> (/var/lib/esmbot/esmBot/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by TheEssem** [comment]
The Chromium instance was stopped a few days ago and I must've forgotten to start it back up, should be good to go now.
