### ISSUE TITLE
ERR_DLOPEN_FAILED when trying to pnpm start the bot

### ISSUE THREAD

**Issue by twardy95** [esmBot/esmBot#335]
### Describe the bug

I followed all the steps provided here: [https://docs.esmbot.net/setup/]()
When I tried running the bot it only shows an error message:
```
node:internal/modules/cjs/loader:1239
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/root/esmBot/node_modules/.pnpm/better-sqlite3@7.6.2/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (/root/esmBot/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
    at new Database (/root/esmBot/node_modules/.pnpm/better-sqlite3@7.6.2/node_modules/better-sqlite3/lib/database.js:48:64)
    at Database (/root/esmBot/node_modules/.pnpm/better-sqlite3@7.6.2/node_modules/better-sqlite3/lib/database.js:11:10)
    at file:///root/esmBot/utils/database/sqlite.js:5:20
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  code: 'ERR_DLOPEN_FAILED'
}
 ELIFECYCLE  Command failed with exit code 1.

```

### Steps to reproduce

Follow all the steps on the setup page. That's literally it and I don't know why it's not working.

### Expected behavior

The bot to run successfully.

### Self-hosted instance?

Yes

### Additional context

I spent over 3 hours trying to get it to work reinstalling node at least 10 times, switching versions, reinstalling all packages/esmBot itself, with no result lol I bet that the answer to this is pretty straightforward unfortunately I'm unable to get it working.

**Comment by TheEssem** [comment]
This is an upstream compatibility issue with Node 19 in better-sqlite3, seems like an update has been released that fixes it now. As such, 345b525 should fix this issue.
