### ISSUE TITLE
Interaction has already been acknowledged

### ISSUE THREAD

**Issue by zewelsh** [esmBot/esmBot#336]
### Command that caused the error

/caption

### Image that caused the error

https://cdn.discordapp.com/attachments/627294660880105472/1051313214333390868/temporary_GIF.gif

### Self-hosted instance?

No

### Error file

Message: DiscordRESTError: Interaction has already been acknowledged. on POST /api/v10/interactions/1051313562657759252/aW50ZXJhY3Rpb246MTA1MTMxMzU2MjY1Nzc1OTI1MjpuNXM4TWY0Z3FqTDBYVUlSTlQzZGp1VW8xMXN1ckFSYXFHMnRtTmpnSExiSWFjSDFZMWl0U1hReHdpdG9vNjJ5SlBLZ3pUd3ZyWlpvS09XdGF5bUNxbWllanNIdlhjMEtHa2RJQnJ1cEdkdm5PZEE5VUtQRHlwcHJnMGxUR1JCNw/callback
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.createMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:151:46)
    at default (file:///root/esmBot/events/interactionCreate.js:30:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 40060,
  method: 'POST',
  resBody: {
    message: 'Interaction has already been acknowledged.',
    code: 40060
  },
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: [Object],
    [Symbol(headers)]: [HeadersList]
  }
}

Stack Trace: DiscordRESTError: Interaction has already been acknowledged. on POST /api/v10/interactions/1051313562657759252/aW50ZXJhY3Rpb246MTA1MTMxMzU2MjY1Nzc1OTI1MjpuNXM4TWY0Z3FqTDBYVUlSTlQzZGp1VW8xMXN1ckFSYXFHMnRtTmpnSExiSWFjSDFZMWl0U1hReHdpdG9vNjJ5SlBLZ3pUd3ZyWlpvS09XdGF5bUNxbWllanNIdlhjMEtHa2RJQnJ1cEdkdm5PZEE5VUtQRHlwcHJnMGxUR1JCNw/callback
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.createMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:151:46)
    at default (file:///root/esmBot/events/interactionCreate.js:30:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TheEssem** [comment]
956f34b4403f7fc20e2a6a68e01fe251784a4904 should resolve this by making sure that interactions are always acknowledged before running a command, therefore avoiding the need for acknowledgement checks and avoiding weird behavior resulting from them.
