### ISSUE TITLE
Bad author image_url

### ISSUE THREAD

**Issue by somerandomcloud** [esmBot/esmBot#337]
### Command that caused the error

/image Joe mama

### Steps to reproduce

1. Run `/image Joe mama`

### Self-hosted instance?

No

### Error file

Message: DiscordRESTError: Invalid Form Body on PATCH /api/v10/webhooks/429305856241172480/aW50ZXJhY3Rpb246MTA1MjU5ODUzOTQ1ODQ0NTMzMzpCbVdDOWxHMk42UGpsTHAzelIwTXZQZ2JSUkNoM1RXclRXb2laZXFFQm9TbDc2MzRybThlQ2M2bWRTeFR0cUhSa2JqTVBjanV1SER1UmdUQURwVVZuckJ1dFlCQUxhaWlYc0pQYTVUUFR2WFB2ZlpBb3l2S01PYnE0b2RXTW1aeg/messages/@​original
 embeds.0.author.icon_url: Not a well formed URL.
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Webhooks.editMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Webhooks.js:116:30)
    at Interactions.editFollowupMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:103:39)
    at Interactions.editOriginalMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:112:21)
    at CommandInteraction.editOriginal (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:201:46)
    at default (file:///root/esmBot/utils/pagination/pagination.js:68:107)
    at ImageSearchCommand.run (file:///root/esmBot/commands/general/image.js?v=21:39:12)
    at runMicrotasks (<anonymous>) {
  code: 50035,
  method: 'PATCH',
  resBody: { code: 50035, errors: [Object], message: 'Invalid Form Body' },
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: [Object],
    [Symbol(headers)]: [HeadersList]
  }
}

Stack Trace: DiscordRESTError: Invalid Form Body on PATCH /api/v10/webhooks/429305856241172480/aW50ZXJhY3Rpb246MTA1MjU5ODUzOTQ1ODQ0NTMzMzpCbVdDOWxHMk42UGpsTHAzelIwTXZQZ2JSUkNoM1RXclRXb2laZXFFQm9TbDc2MzRybThlQ2M2bWRTeFR0cUhSa2JqTVBjanV1SER1UmdUQURwVVZuckJ1dFlCQUxhaWlYc0pQYTVUUFR2WFB2ZlpBb3l2S01PYnE0b2RXTW1aeg/messages/@​original
 embeds.0.author.icon_url: Not a well formed URL.
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Webhooks.editMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Webhooks.js:116:30)
    at Interactions.editFollowupMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:103:39)
    at Interactions.editOriginalMessage (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:112:21)
    at CommandInteraction.editOriginal (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:201:46)
    at default (file:///root/esmBot/utils/pagination/pagination.js:68:107)
    at ImageSearchCommand.run (file:///root/esmBot/commands/general/image.js?v=21:39:12)
    at runMicrotasks (<anonymous>)

**Comment by somerandomcloud** [comment]
To add to it all

![image](https://user-images.githubusercontent.com/39058370/207629616-7522817b-625d-420d-be6b-68bcef16df43.png)

**Comment by teo0781** [comment]
Unable to replicate on my end, mind sending your discord profile picture? Seems like it could be the issue

**Comment by somerandomcloud** [comment]
Profile picture: `https://cdn.discordapp.com/avatars/702973430449832038/a_7e62011a0196bdc1b9b4b17d36bab3fa.gif`

**Comment by TheEssem** [comment]
Are you in the support server? If so, can you try running the command in the bot-cmds channel and then ping me with the result?

**Comment by somerandomcloud** [comment]
Just pinged you, and provided some extra context

**Comment by TheEssem** [comment]
This ended up being an upstream Oceanic issue. It should be fixed with commit https://github.com/OceanicJS/Oceanic/commit/3578b207e87dbe908ed21ce299a309629f91b854, but may take a bit to appear in a release. For now, I've gone ahead and patched it manually on the main bot.
