### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by sneezy-silly** [esmBot/esmBot#338]
### Command that caused the error

/music play query nights and reala

### Steps to reproduce

1. Enter "/music play" on Discord desktop application
2. Click on the prompt "/music play"
3. Fill out the query with "nights and reala"
4. Press enter
5. Scroll up
6. See the error
7. Download text file

### Self-hosted instance?

Yes

### Error file

```
Message: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:173:46)
    at MusicAIOCommand.acknowledge (file:///root/esmBot/classes/command.js:54:30)
    at MusicAIOCommand.run (file:///root/esmBot/commands/music/music.js?v=99:9:16)
    at default (file:///root/esmBot/events/interactionCreate.js:27:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 10062,
  method: 'POST',
  resBody: { message: 'Unknown interaction', code: 10062 },
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: [Object],
    [Symbol(headers)]: [HeadersList]
  }
}

Stack Trace: DiscordRESTError: Unknown interaction
    at RequestHandler.request (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:95:15)
    at RequestHandler.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:80:21)
    at RESTManager.authRequest (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Interactions.createInteractionResponse (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/routes/Interactions.js:68:29)
    at CommandInteraction.defer (/root/esmBot/node_modules/.pnpm/oceanic.js@​1.3.1_bufferutil@​4.0.7/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:173:46)
    at MusicAIOCommand.acknowledge (file:///root/esmBot/classes/command.js:54:30)
    at MusicAIOCommand.run (file:///root/esmBot/commands/music/music.js?v=99:9:16)
    at default (file:///root/esmBot/events/interactionCreate.js:27:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections  #(node:internal/process/task_queues:96:5)
```

### Additional context

The music still works as usual, as long as one doesn't post links or long titles. Most of the music commands yield errors as well. Some titles cannot be found and still return an error report. Server is my own, and bot appears to have all the permissions needed to play music, as it did so earlier.

**Comment by TheEssem** [comment]
956f34b4403f7fc20e2a6a68e01fe251784a4904 should partially resolve this, though more testing is needed.

**Comment by TheEssem** [comment]
It appears that the error is now being caught before it can cause any more issues. Closing as fixed.
