### ISSUE TITLE
caption not working 

### ISSUE THREAD

**Issue by yeaboi19** [esmBot/esmBot#348]
### Command that caused the error

caption

### Image that caused the error

https://cdn.discordapp.com/attachments/764770346800250913/1061681514938634282/watermark.png

### Steps to reproduce

1. Go to 'image'
2. Right Click on 'image'
3. Scroll down to 'choose image'
4. Choose image
5. Type /caption sugma cock
6. Shows error

### Self-hosted instance?

No

### Error file

```
Message: BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/client.js:906:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_BODY_TIMEOUT'
}

Stack Trace: BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/client.js:906:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7)
```

### Additional context

amogus :)

**Comment by TheEssem** [comment]
Haven't seen this in the wild since over a year ago, assuming this is fixed.
