### ISSUE TITLE
It told me to do this

### ISSUE THREAD

**Issue by DrakosGata** [esmBot/esmBot#358]
### Describe the bug

Message: TypeError: Cannot read properties of undefined (reading 'permissionsOf')
    at play (file:///root/esmBot/utils/soundplayer.js:56:21)
    at PlayCommand.run (file:///root/esmBot/commands/music/play.js?v=101:26:14)
    at MusicAIOCommand.run (file:///root/esmBot/commands/music/music.js?v=99:19:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///root/esmBot/events/interactionCreate.js:28:20)

Stack Trace: TypeError: Cannot read properties of undefined (reading 'permissionsOf')
    at play (file:///root/esmBot/utils/soundplayer.js:56:21)
    at PlayCommand.run (file:///root/esmBot/commands/music/play.js?v=101:26:14)
    at MusicAIOCommand.run (file:///root/esmBot/commands/music/music.js?v=99:19:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///root/esmBot/events/interactionCreate.js:28:20)

### Steps to reproduce

1. use /music play [query] of Discord

2. type "Infestation"

3. Encounter bug report

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Should be fixed with 3ed65c3, which should (hopefully) appear by the end of this month on the main bot; for now, you can probably try using a different voice channel
