### ISSUE TITLE
/bandicam timeout

### ISSUE THREAD

**Issue by geedo7** [esmBot/esmBot#364]
Message: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:133:24)
    at /root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:80:46
    at Immediate._onImmediate (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:121:9)
    at processImmediate (node:internal/timers:466:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}

Stack Trace: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:133:24)
    at /root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:80:46
    at Immediate._onImmediate (/root/esmBot/node_modules/.pnpm/undici@​5.12.0/node_modules/undici/lib/core/connect.js:121:9)
    at processImmediate (node:internal/timers:466:21)

**Comment by TheEssem** [comment]
This was caused by backend issues with my server provider on the main instance. Should be fixed now.
