### ISSUE TITLE
Gif captioning error

### ISSUE THREAD

**Issue by KirbyKing186** [esmBot/esmBot#380]
### Command that caused the error

/caption text: my fuckin god bruh are you fucking seeing this shit image: [attachment]

### Image that caused the error

https://i.imgur.com/MNcmvzs.gif

### Steps to reproduce

1. Go to 'esmbot discord'
2. Use /caption on a gif attachment
3. Wait 5 seconds

### Self-hosted instance?

No

### Error file

```

Message: Error: Timed out
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

Stack Trace: Error: Timed out
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

```

### Additional context

.gif file is 14MB

**Comment by TheEssem** [comment]
Timeouts tend to happen, but they shouldn't be throwing an error. A nicer message has been added with https://github.com/esmBot/esmBot/commit/3244b9c483f9c96d0ad3e4de51bb63f550275858.
