### ISSUE TITLE
/speechbubble only accepts .jpg files

### ISSUE THREAD

**Issue by 0x5066** [esmBot/esmBot#391]
### Describe the bug

Trying to give the bot anything that isn't a .jpg image through the /speechbubble command will result in two errors.

When directly copypasting:

```
Message: Error: vips_image_get: field "exif-data" not found
vips_image_get: field "exif-data" not found
vips_image_get: field "exif-data" not found

    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:66:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45)
```

When uploading a standalone .png file (either through drag'n'dropping or by selecting a file through the file explorer)

```
Message: Error: vips_image_get: field "exif-data" not found

    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:66:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.13.0/node_modules/<redacted>/lib/websocket.js:1184:20)
```

### Steps to reproduce

1. Upload a .png file when using the /speechbubble command (may happen with other commands)
2. Press enter
3. See the error message occur

### Expected behavior

The /speechbubble command is supposed to take any file format and not just limit itself to .jpg.

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
My fault, for some reason there were two different versions of libvips on the image servers and it was creating a conflict. Should be fixed now.
