### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by GuiMiTomo** [esmBot/esmBot#399]
### Command that caused the error

/speed

### Image that caused the error

https://media.discordapp.net/ephemeral-attachments/991195178507448408/1126902084801937579/We_are_going_to_beat_you_to_death.gif

### Self-hosted instance?

No

### Error file

Message: Error: Timed out when requesting https://media.discordapp.net/ephemeral-attachments/991195178507448408/1126902084801937579/We_are_going_to_beat_you_to_death.gif
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async SpeedCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

Stack Trace: Error: Timed out when requesting https://media.discordapp.net/ephemeral-attachments/991195178507448408/1126902084801937579/We_are_going_to_beat_you_to_death.gif
    at getType (file:///home/esmBot/esmBot/utils/image.js:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (file:///home/esmBot/esmBot/utils/imagedetect.js:99:30)
    at async default (file:///home/esmBot/esmBot/utils/imagedetect.js:150:24)
    at async SpeedCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:36)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

**Comment by TheEssem** [comment]
Should be fixed with 478e877ad65c4d430b2c43c4c37fc6523086a19d

**Comment by thepwrtank18** [comment]
![image](https://github.com/esmBot/esmBot/assets/57580668/da7a00d1-6d99-4e5a-a5cd-6c1efa759d39)

**Comment by TheEssem** [comment]
> ![image](https://github.com/esmBot/esmBot/assets/57580668/da7a00d1-6d99-4e5a-a5cd-6c1efa759d39)
> 

This message is intentional, timeouts happen when a web server takes too long to respond and aren't fixable on the bot's end. Note the advice given in the message.
