### ISSUE TITLE
DiscordRESTError: Missing Access

### ISSUE THREAD

**Issue by Tobost06** [esmBot/esmBot#419]
### Command that caused the error

/caption

### Image that caused the error

https://tenor.com/view/cat-pog-moment-swaggers-gif-20558299

### Steps to reproduce

1. Go to Server with the bot in it
2. Post the gif in chat
3. Do the command
4. Get error in chat

### Self-hosted instance?

Yes

### Error file

Message: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20) {
  code: 50001
}

Stack Trace: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

**Comment by TheEssem** [comment]
Fixed in 2dad6960a25d81280ea5b807485a3425173bd2aa.
