### ISSUE TITLE
Caption (maybe more) error

### ISSUE THREAD

**Issue by realNotNikita** [esmBot/esmBot#421]
### Command that caused the error

/caption

### Image that caused the error

https://media.discordapp.net/attachments/1176930910105522208/1188098482431606854/togif.gif?ex=659949f0&is=6586d4f0&hm=45598b6c74e9f75f9a906aa943f81eb7cdaf02fc3d2d0e8e03da17067c61cfac&=&width=716&height=956

### Steps to reproduce

1. Reply to an image
2. Use the /caption in the reply
3. Write your text
4. Error

### Self-hosted instance?

Yes

### Error file

Message: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20) {
  code: 50001
}

Stack Trace: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.7.1/node_modules/oceanic.js/dist/lib/routes/Channels.js:447:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:149:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

**Comment by ioletsgo** [comment]
Its a Missing Access error, meaning that it cannot engage with the command in one way or another. Have you made sure that the bot can access the specific channel and messages posted in that channel?
