### ISSUE TITLE
/music play command giving a node error

### ISSUE THREAD

**Issue by Existence-dev** [esmBot/esmBot#427]
### Command that caused the error

/music play query: at dooms gate

### Steps to reproduce

1. /music play query: at dooms gate

### Self-hosted instance?

No

### Error file

Message: Error: No nodes available, please add a node first
    at Shoukaku.getNode (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​3.4.0/node_modules/shoukaku/dist/index.mjs:1271:13)
    at play (file:///home/esmBot/esmBot/utils/soundplayer.js:59:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=100:19:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

Stack Trace: Error: No nodes available, please add a node first
    at Shoukaku.getNode (file:///home/esmBot/esmBot/node_modules/.pnpm/shoukaku@​3.4.0/node_modules/shoukaku/dist/index.mjs:1271:13)
    at play (file:///home/esmBot/esmBot/utils/soundplayer.js:59:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MusicAIOCommand.run (file:///home/esmBot/esmBot/commands/music/music.js?v=100:19:23)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

### Additional context

It seems like there was nothing done before it was giving the error. We just tryed playing music in a vc and it would give this error.

**Comment by TheEssem** [comment]
Seems like there were some Lavalink issues with the main instance. Should be resolved now.

**Comment by Existence-dev** [comment]
I tried removing and readding it and changing con

> Seems like there were some Lavalink issues with the main instance. Should be resolved now.

Thanks
