### ISSUE TITLE
/soundboard on "Marriage Bot"

### ISSUE THREAD

**Issue by DaRealLevi11** [esmBot/esmBot#435]
### Describe the bug

The bot just say's
Message: TypeError: voiceChannel.permissionsOf is not a function
    at play (file:///home/esmBot/esmBot/utils/soundplayer.js:57:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SoundboardAIOCommand.run (file:///home/esmBot/esmBot/commands/soundboard/soundboard.js?v=121:15:12)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)

Stack Trace: TypeError: voiceChannel.permissionsOf is not a function
    at play (file:///home/esmBot/esmBot/utils/soundplayer.js:57:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SoundboardAIOCommand.run (file:///home/esmBot/esmBot/commands/soundboard/soundboard.js?v=121:15:12)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:37:20)
    In the code, could anyone perhaps fix this

### Steps to reproduce

1. Go to Any Discord Server with the bot in it
2. Use /soundboard [sfx]
3. See error

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Soundboard commands have been removed from the esmBot source tree and will soon be removed from the main instance as well due to Discord introducing their own soundboard system.
