### ISSUE TITLE
swirl error 

### ISSUE THREAD

**Issue by c4tma4sk** [esmBot/esmBot#438]
### Command that caused the error

/swirl

### Image that caused the error

https://media.discordapp.net/attachments/1147342901760770169/1216990320957456456/reddit.jpg?ex=6602658f&is=65eff08f&hm=f3e87a8d211fff8fd4fd37725f35f045a661c5ac85fc1f20240d0354c9017cb3&

### Self-hosted instance?

Yes

### Error file

```
Message: Error: VipsJpeg: out of order read at line 792

VipsJpeg: out of order read at line 792

VipsJpeg: out of order read at line 792

at ImageConnection.onMessage

(file:///home/esmBot/esmBot/utils/imageConnection.js:66:22) at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45) at WebSocket.emit (node: events: 518:28)

at Receiver.receiverOnMessage

(/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@ 8.13.0/node_modules/<redacted>/lib/websocket.js:1184:20) at Receiver.emit (node:events: 518:28) at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@

8.13.0/node_modules/<redacted>/lib/receiver.js: 526:14) at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@ 8.13.0/node_modules/<redacted>/lib/receiver.js:459:17) at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@

8.13.0/node_modules/<redacted>/lib/receiver.js:158:22) at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@ 8.13.0/node_modules/<redacted>/lib/receiver.js:84:10)

at writeOrBuffer (node: internal/streams/writable: 564:12)

Stack Trace: Error: VipsJpeg: out of order read at line 792

VipsJpeg: out of order read at line 792 VipsJpeg: out of order read at line 792

at ImageConnection.onMessage

(file:///home/esmBot/esmBot/utils/imageConnection.js:66:22)

at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:89:45)

at WebSocket.emit (node:events: 518:28)

( at Receiver.receiverOnMessage

/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@ 8.13.0/node_modules/<redacted>/lib/websocket.js:1184:20)

at Receiver.emit (node: events: 518:28)

at Receiver.dataMessage

(/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@

8.13.0/node_modules/<redacted>/lib/receiver.js: 526:14)

at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@

8.13.0/node_modules/<redacted>/lib/receiver.js:459:17)

at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@ 8.13.0/node_modules/<redacted>/lib/receiver.js:158:22)

at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@

8.13.0/node modules/<redacted>/lib/receiver.js: 84:10)

at writeOrBuffer (node:internal/streams/writable: 564:12)
```

**Comment by TheEssem** [comment]
Already fixed in next release with 2a54cbfc52a451cd3c3312a458455ff762d87de4
