### ISSUE TITLE
I tried putting a caption to a gif, turned out a error

### ISSUE THREAD

**Issue by NicoAlc03** [esmBot/esmBot#451]
### Command that caused the error

/caption

### Self-hosted instance?

Yes

### Error file

```
Message: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/routes/Channels.js:498:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:175:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:44:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:38:20) {
  code: 50001
}

Stack Trace: DiscordRESTError: Missing Access
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Channels.get (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@1.10.4_patch_hash=33xic76zksio6aql4xyg3biije/node_modules/oceanic.js/dist/lib/routes/Channels.js:498:30)
    at default (file:///home/esmBot/esmBot/utils/imagedetect.js:175:100)
    at CaptionCommand.run (file:///home/esmBot/esmBot/classes/imageCommand.js:44:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/esmBot/esmBot/events/interactionCreate.js:38:20)
```

**Comment by TheEssem** [comment]
Should be fixed in 8ac5894
