### ISSUE TITLE
qrcreate generates error message if data is too big

### ISSUE THREAD

**Issue by DatHam** [esmBot/esmBot#475]
### Command that caused the error

qrcreate

### Steps to reproduce

1. use qrcreate with a lot of text

### Self-hosted instance?

No

### Error file

```
Message: Error: Data too big
    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:75:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:102:45)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:569:14)
    at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:496:10)
    at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:167:16)
    at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:564:12)

Stack Trace: Error: Data too big
    at ImageConnection.onMessage (file:///home/esmBot/esmBot/utils/imageConnection.js:75:22)
    at WebSocket.<anonymous> (file:///home/esmBot/esmBot/utils/imageConnection.js:102:45)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:569:14)
    at Receiver.getData (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:496:10)
    at Receiver.startLoop (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:167:16)
    at Receiver._write (/home/esmBot/esmBot/node_modules/.pnpm/<redacted>@​8.18.0_bufferutil@​4.0.8/node_modules/<redacted>/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:564:12)
```

**Comment by atommy3** [comment]
This error occurred because a QR code can only encode up to 2953 bytes, but the qrcreate command allowed for up to 4096 characters to be provided. A fix for this has been proposed in pull request [482](https://github.com/esmBot/esmBot/pull/482>).

**Comment by TheEssem** [comment]
Fixed with ce1dc57394a08af71dd4bd1370ac2575bf9ced34
