### ISSUE TITLE
HTTP Error  Discord

### ISSUE THREAD

**Issue by WellRightPlay91724** [esmBot/esmBot#478]
### Command that caused the error

/legend

### Steps to reproduce

2. Click on '......'

### Self-hosted instance?

Yes

### Error file

Message: DiscordHTTPError: 520 status code 520
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Webhooks.execute (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/routes/Webhooks.js:167:30)
    at Interactions.createFollowupMessage (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/routes/Interactions.js:20:39)
    at CommandInteraction.createFollowup (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:152:61)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:77:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Stack Trace: DiscordHTTPError: 520 status code 520
    at RequestHandler.request (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:96:15)
    at RequestHandler.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RequestHandler.js:81:21)
    at RESTManager.authRequest (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/rest/RESTManager.js:47:29)
    at Webhooks.execute (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/routes/Webhooks.js:167:30)
    at Interactions.createFollowupMessage (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/routes/Interactions.js:20:39)
    at CommandInteraction.createFollowup (/home/esmBot/esmBot/node_modules/.pnpm/oceanic.js@​1.11.2_patch_hash=3nhztltpqv4jjckzf2rx35up3u_bufferutil@​4.0.8/node_modules/oceanic.js/dist/lib/structures/CommandInteraction.js:152:61)
    at default (file:///home/esmBot/esmBot/events/interactionCreate.js:77:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Additional context

Problems Error HTTP Discord

**Comment by TheEssem** [comment]
Error code 520 is a Cloudflare-specific error code indicating a server issue, in this case on Discord's end. Unfortunately, there's not really anything that can be done on the bot's end to address it.
